server:
  ##Eureka 默认端口
  port: 8030
eureka:
  client:
    serviceUrl:
      ##支持并连接Ureka服务端
      defaultZone: http://user:password123@localhost:8761/eureka
spring:
  application:
    ##配置应用名称
    name: micorservice-hystrix-turbine

turbine:
  aggregator:
    ##指定聚合哪些集群，多个使用“，”分割，默认为default（表示全部聚合）。可使用 http://localhost:8030/turbine.stream?cluster={clusterConfig之一}访问
    ##填写应用名称对应Eureka控制面板服务列表中的application列或微服务的String.application.name（VIP） 全大写
    cluster-config: MICROSERVICE-CONSUMER-MOVICE-RIBBON-WITHIN-HYSTRIX2
    ###配置EUreka中的serviceID列表，表明监控哪些服务监控，哪些服务多个使用","分割
    ###填写应用实例名称前缀，对应Eureka控制面板列表中的Status列，前缀不包含端口。默认全小写
  app-config: microservice-consumer-movice-ribbon-within-hystrix2
  ##此表达式是一个Spring EL表达式 此处写法new String("default")与“'default'”作用一样
#  cluster-name-expression: "'default'"

##设置被监控的服务前缀为/ribbion(applicationName) ,设置此属性时不能设置cluster-name-expression
turbine.instanceUrlSuffix.MICROSERVICE-CONSUMER-MOVICE-RIBBON-WITHIN-HYSTRIX2: /ribbon/hystrix.stream


##  1.turbine.combine-host-port参数设置为true，可以让同一主机上的服务通过主机名与端口号的组合来进行区分，默认情况下会以host来区分不同的服务，这会使得在本机调试的时候，本机上的不同服务聚合成一个服务来统计。


###设置turbine 日志
logging:
  level:
    root: INFO
    com.netflex.turbine.monitor: BEBUG

## 1.设置turbineDEBUG日志后可以从日志中查看被监控服务的监控路径：   c.n.t.monitor.instance.InstanceMonitor   : Url for host: http://192.168.43.94:8010/actuator/hystrix.stream MICROSERVICE-CONSUMER-MOVICE-RIBBON-WITHIN-HYSTRIX2
## 2.如果不指定被监控服务的前缀的话（使用该配置：turbine.instanceUrlSuffix.MICROSERVICE-CONSUMER-MOVICE-RIBBON-WITHIN-HYSTRIX2） 默认是从根路径拼接/actuator/hysrix.stream