server:
  ##Eureka 默认端口
  port: 8030
eureka:
  client:
    serviceUrl:
      ##支持并连接Ureka服务端
      defaultZone: http://user:password123@localhost:8761/eureka
spring:
  application:
    ##配置应用名称
    name: micorservice-hystrix-turbine

turbine:
  aggregator:
    ##指定聚合哪些集群，多个使用“，”分割，默认为default（表示全部聚合）。可使用 http://localhost:8030/turbine.stream?cluster={clusterConfig之一}访问
    ##填写应用名称对应Eureka控制面板服务列表中的application列或微服务的String.application.name（VIP） 全大写
    cluster-config: default
    ###配置EUreka中的serviceID列表，表名监控哪些服务
    ###填写应用实例名称前缀，对应Eureka控制面板列表中的Status列，前缀不包含端口。默认全小写
  app-config: microservice-consumer-movice-ribbon-within-hystrix,microservice-consumer-movice-feign-within-hystrix
  ##此表达式是一个Spring EL表达式 此处写法new String("default")与“'default'”作用一样。可以指定为被监控的服务的元数据，表示监控这些服务
  ##turbine.cluster-name-expression参数指定了集群名称为default，当服务数量非常多的时候，可以启动多个Turbine服务来构建不同的聚合集群，而该参数可以用来区分这些不同的聚合集群用于指定集群名称，当服务数量非常多的时候，可以启动多个Turbine服务来构建不同的聚合集群，而该参数可以用来区分这些不同的聚合集群，同时该参数值可以再Hystrix仪表盘中用来定位不同的聚合集群，只需在Hystrix Stream的URL中通过cluster参数来指定 当clusterNameExpression: metadata['cluster']时，假设想要监控的应用配置了eureka.instance.metadata-map.cluster: ABC，则需要配置，同时turbine.aggregator.clusterConfig: ABC turbine.combine-host-port参数设置为true，可以让同一主机上的服务通过主机名与端口号的组合来进行区分，默认情况下会以host来区分不同的服务，这会使得在本机调试的时候，本机上的不同服务聚合成一个服务来统计。
  cluster-name-expression: "'default'"
