server:
  #服务端口7901
  port: 7906
eureka:
  client:
    healthcheck:
      #使用health端点来代替心跳表明服务是否可用，反应到eureka server ui上服务是的UP还是DOWN
      enabled: true
    serviceUrl:
      ##支持并连接Ureka服务端
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    ##默认使用主机名称访问设置成使用IP地址做为服务提供路径
    prefer-ip-address: true
    ##使用“应用名称：实例IE：端口号”的组合显示实例ID
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

##配置actuator监控系统健康情况
management:
  endpoints:
    web:
      exposure:
        ##测试环境下暴露所有端点(暴露/health等路径，系统健康信息等全部暴露不太安全)  * 在yaml 文件属于关键字，所以需要加引号
        include: "*"
########################################################################################
##DIY
user:
  userServicePath: http://localhost:8080/simple/
########################################################################################
spring:
  application:
    name: microservice-consumer-movice

###只使用ribbon不使用eureka：1.禁用eureka.2.添加ribbon服务列表
ribbon:
  eureka:
    enabled: false

##设置需要被ribbion负载均衡的服务名称
microservice-provider-user:
  ribbon:
    ##设置当前需要被ribbon负载均衡的服务列表对应的端口及路径
    listOfServers: localhost:7905

logging:
  ##日志级别
  level:
    ##根级别显示info
    root: INFO
    ##下面三行表显示sql并把参数打印出来
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    ##application下显示DEBUG
    com.wonders: DEBUG