server:
  ##Eureka 默认端口
  port: 8030
eureka:
  client:
    serviceUrl:
      ##支持并连接Ureka服务端
      defaultZone: http://user:password123@localhost:8761/eureka
spring:
  application:
    ##配置应用名称
    name: micorservice-hystrix-turbine3

turbine:
  aggregator:
    ##指定聚合哪些集群，多个使用“，”分割，默认为default（表示全部聚合）。可使用 http://localhost:8030/turbine.stream?cluster={clusterConfig之一}访问
    ##填写应用名称对应Eureka控制面板服务列表中的application列或微服务的String.application.name（VIP） 全大写
    cluster-config: MICROSERVICE-CONSUMER-MOVICE-RIBBON-WITHIN-HYSTRIX3
    ###配置EUreka中的serviceID列表，表明监控哪些服务监控，哪些服务多个使用","分割
    ###填写应用实例名称前缀，对应Eureka控制面板列表中的Status列，前缀不包含端口。默认全小写
  app-config: microservice-consumer-movice-ribbon-within-hystrix3
  ##此表达式是一个Spring EL表达式 此处写法new String("default")与“'default'”作用一样
#  cluster-name-expression: "'default'"

##设置被监控的服务前缀为/ribbion(applicationName) ,设置此属性时不能设置cluster-name-expression
##此处有个BUG，当被监控服务同时设置metadata-map: management.server.port: 8081(管理端口：用于交给eureka暴露给其它服务) 和 management.server.port: 8081 时 管理端口变成了8081,并且无论home-page-url-path: /ribbon是否指定   turbine的监控路径都不会以/applicationNmae开头，变成了/actuator开头追加/hystrix.stream
turbine.instanceUrlSuffix.MICROSERVICE-CONSUMER-MOVICE-RIBBON-WITHIN-HYSTRIX3: /actuator/hystrix.stream


##  1.turbine.cluster-name-expression: 用于指定集群名称，当服务数量非常多的时候，可以启动多个Turbine服务来构建不同的聚合集群，而该参数可以用来区分这些不同的聚合集群，同时该参数值可以在Hystrix仪表盘中用来定位不同的聚合集群，
##  2.只需在Hystrix Stream的URL中通过cluster参数来指定 http://localhost:8030/turbine.stream?cluster={clusterConfig之一}访问
##  3.当clusterNameExpression: metadata['cluster']时，假设想要监控的应用配置了eureka.instance.metadata-map.cluster: ABC，则需要配置，同时turbine.aggregator.clusterConfig: ABC

##  1.turbine.combine-host-port参数设置为true，可以让同一主机上的服务通过主机名与端口号的组合来进行区分，默认情况下会以host来区分不同的服务，这会使得在本机调试的时候，本机上的不同服务聚合成一个服务来统计。


###设置turbine 日志
logging:
  level:
    root: INFO
    com.netflex.turbine.monitor: BEBUG

## 1.设置turbineDEBUG日志后可以从日志中查看被监控服务的监控路径：   c.n.t.monitor.instance.InstanceMonitor   : Url for host: http://192.168.43.94:8010/actuator/hystrix.stream MICROSERVICE-CONSUMER-MOVICE-RIBBON-WITHIN-HYSTRIX2
## 2.如果不指定被监控服务的前缀的话（使用该配置：turbine.instanceUrlSuffix.MICROSERVICE-CONSUMER-MOVICE-RIBBON-WITHIN-HYSTRIX2） 默认是从根路径拼接/actuator/hysrix.stream